blogTitle = "Geniusgordon"
blogUrl = "https://geniusgordon.github.io"
authorName = "Gordon Ueng"
profilePic = "https://www.gravatar.com/avatar/c120f55cea58c16e941500789f1e2bb1?size=512"
linkPrefix = "/"
github = "https://www.github.com/geniusgordon"
facebook = "https://www.facebook.com/geniusgordon"
twitter = "https://www.twitter.com/geniusgordon"
linkedin = "https://www.linkedin.com/in/geniusgordon/"
